name: PRs to master
on: 
  pull_request:
    branches: [production]
    types: [closed]
jobs:
  merge-production-back-to-development:
    if: github.event.pull_request.merged == true
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set Git config
      run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
    - name: Merge production back to development
      run: |
          git fetch --unshallow
          git checkout development
          git pull
          git merge --no-ff production -m "Auto-merge production back to development"
          git push
